hunav_evaluator_node:
  ros__parameters:
    mode: 2
    frequency: 0.0
    result_file: "metrics_dwb"
    experiment_tag: "dwb_test"
    use_nav_goal_to_start: True
    
    metrics:
      time_to_reach_goal: True
      path_length: True
      cumulative_heading_changes: True
      avg_distance_to_closest_person: True
      minimum_distance_to_people: True
      maximum_distance_to_people: True
      intimate_space_intrusions: True
      personal_space_intrusions: True
      social_space_intrusions: True
      group_intimate_space_intrusions: True
      group_personal_space_intrusions: True
      group_social_space_intrusions: True
      completed: True
      minimum_distance_to_target: True
      final_distance_to_target: True
      robot_on_person_collision: True
      person_on_robot_collision: True
      time_not_moving: True
      avg_robot_linear_speed: True
      avg_robot_angular_speed: True
      avg_acceleration: True
      avg_overacceleration: True
      avg_pedestrian_velocity: True
      avg_closest_pedestrian_velocity: True
      social_force_on_agents: True
      social_force_on_robot: True
      social_work: True